dist: trusty
env:
  global:
    - secure: "gH9zypWZnvgKgQLzBBeMxZJKgT1M23n6blSmx4BoHqaRcDmCfzEWpfcHJxLLVKrtd5PoMnumKp6237z01n9cWWJc3w5EZ5gAWxMwcrZznm4Ty1/urmCu7SkbbLxJtWgc1GgzsqrXLusxM7dpw66ewJr/heZbCsqlKptGH3oHlqFZlCDYNSkR7zJ7imOmfc3zBA4h3PJfN2xhuSNdHjJg/xa8kZsNJY77VtLfr256GZhrfZqAzl1EaKu6xzeqwauRevBWb87TgI4/nxn4uFAp6JH7fgo/lZbsiTkXwp/eF5pB6MuJiz6U0soGvOs0CEp5wHzcOiVs7nNYkivHRwZaAeqkjFKa+Eixg3pTK51Qm5bWw77kzFpIrEMJ2KCBOqGRmtWS6YwKPDKmZkBRnlnPe2lEWnqsl1fIb9ew2V1Iigf4htbBrllZyFrKKLYlmOfQDdFCkekDsCN7rcIu1V+Ybe+DOYKrTf02VDTz4KHAgfWmYbsKM+Kt/phBI529/J13J0d5bWkK4qvEAws+B6paJ5b2kE04Dm8FUE3JQ4fX4Afh20F/zlZBTCqi9mBLKA0eV9EoD9y76CMI9O+g+v/hBDI8Xh5iSDodEN5W08f6Npq6GyN7fJ2sfbqMtANOxS2xzMHIahLnfsVnSqcNclYip3PkoYHIFb3lFk37BlId+h4="
script: 
  - git clone https://github.com/elasticdog/transcrypt.git
  - cd transcrypt && sudo ln -s ${PWD}/transcrypt /usr/local/bin/transcrypt && cd ..
  - transcrypt -F -y -c aes-256-cbc -p ${MASTER_PASSWORD}
  - sudo apt-add-repository -y ppa:ansible/ansible && sudo apt-get -y -qq update -o=Dpkg::Use-Pty=0 && apt-get -y -qq install -o=Dpkg::Use-Pty=0 ansible jq
  - cd ansible && ./provision.sh
branches:
  only:
    - master
notifications:
  slack:
    secure: Kw1QbqtA1XfJ7XOWLxemixxGkRi/6q/lnTfn37xFiOlEZupO2NR6T4ENQRWkP/oIrLKX1PxXjHk+ff2eshKcFyktGJjf3fKuC1dFSLBhcD2uq2VCII1u3/IKUAMaUyz+rXVhcyV8MgUHBF+7vpqaxKrnB/kuiuPKnMhx7vhANohGUmEWPPl52ieCj1gj7c4961kXXB80ky6qzkkOXWLF05AEmTRvNKbbep1YsjWV2pJgnA50tGER3M24Hn5oxBPKWPGWjVEs9vGQT/eiIcm22OIz7g6UsjQphDWmZLyP80A6WRzXMe7aqYV0U8cUAvPX+wD3xTA691v1OorAHU9Mg3cpJqIYql5uy9HjhMj1K9rkzM0a9OxWhISJnLWO0dW83zjLL1vAnOQtoQOB2aqxRsgRYaXkVCcU29h7Gn1LHX6bTJbXkNX140ApYGtj1AlOPVNpx4lBE6K7LVJW1IOevtxzJnp7phAls0BQKSy5bec9/OaSqfU9UoZREc9+wijq9Uy/NNHu7BZNNy3C3hs1Segemk7ZbM9+cxRUCNeskugOhOf65fyMUOusQZi2KS4Ff3p1VtekymN8xtIH9oQrBcowdubZ8izTkoTxGuTaklcqXWV52ug/tjSJjr6XhryafbtX/75QEqSmL8kRHLajunsw42hF6e0hzkMg0mNuZn8=
