---

- name: Get EC2 Instance Metadata 
  action: ec2_facts

- name: Get CodeDeploy
  get_url:
    url: "https://aws-codedeploy-{{ ansible_ec2_placement_region }}.s3.amazonaws.com/latest/install"
    dest: /tmp/codedeploy-install

- name: CodeDeploy Install Binary 
  file:
    state: file
    path: /tmp/codedeploy-install
    mode: 0777

- name: CodeDeploy Install
  become: true
  command: /tmp/codedeploy-install auto creates=/opt/codedeploy-agent/bin/codedeploy-agent

- name: Configure CloudWatch
  template:
    dest: /etc/awslogs.conf
    group: root
    mode: 0600
    owner: root
    src: awslogs.conf.j2
  notify: 
    - restart cloudwatch

- name: Download AWS CloudWatch installer
  get_url:
    dest: /tmp/awslogs-agent-setup.py
    group: root
    owner: root
    mode: 0600
    url: https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py

- name: Install AWS CloudWatch agent
  shell: python /tmp/awslogs-agent-setup.py -n -r {{ ansible_ec2_placement_region }} -c /etc/awslogs.conf creates=/etc/init.d/awslogs


